### ISSUE TITLE
[Bug] Add TFC nutrition values to PH foods

### ISSUE THREAD

**Issue by RisingInIris2017** [Lebeg134/TFC-PH_Compat#3] opened 2021-03-24 14:56 UTC
### TFC_PH_Compat Mod Version:
1.1.0
### Descriptions of suggestion:
I have installed these mods shown in the picture below:
![QQ图片20210324225322](https://user-images.githubusercontent.com/28519848/112331287-bebe0d80-8cf3-11eb-8afa-1aa4d1a604fd.png)
But after I checked the PH foods in the game, I found that TFC_PH_Compat Mod did not add TFC nutrition values to PH foods, which should be added.
![2021-03-24_22 03 23](https://user-images.githubusercontent.com/28519848/112331520-f0cf6f80-8cf3-11eb-9183-baacd2cf5029.png)
![2021-03-24_22 03 15](https://user-images.githubusercontent.com/28519848/112331528-f2993300-8cf3-11eb-9a64-09a00f8d5a71.png)
I think it is helpful to report this issue to you, so I post it here.
Thanks for your patient and kindhearted help in advance.

**Comment by Lebeg134** [comment] 2021-03-24 20:53
Hey can you add me on Discord to discuss this bug in more detail? my Discord is Lebeg134#3036

**Comment by drhaber** [comment] 2021-03-25 22:11
I have noticed this issue as well as all PH food has a 21 day decay

Food added by this mod
<img width="542" alt="Screen Shot 2021-03-25 at 6 09 42 PM" src="https://user-images.githubusercontent.com/56454522/112550134-47d95100-8d95-11eb-9d21-ac80ce08f711.png">

Food added by PH
<img width="361" alt="Screen Shot 2021-03-25 at 6 10 36 PM" src="https://user-images.githubusercontent.com/56454522/112550212-67707980-8d95-11eb-82a5-2c81b1f10754.png">

Added by me via Craft Tweaker
<img width="408" alt="Screen Shot 2021-03-25 at 6 11 39 PM" src="https://user-images.githubusercontent.com/56454522/112550310-8d961980-8d95-11eb-8337-5fdbb7a160a7.png">

**Comment by RisingInIris2017** [comment] 2021-03-26 03:26
> Lebeg134#3036

I have sent my Discord adding request to you.
My Discord ID is Project PH03-nix#5759 .

**Comment by Lebeg134** [comment] 2021-03-27 17:29
Can you guys check out a few thing for me?  Does tfc-ph_compat uncooked items have nutritional data? (I see drhaber has) Does Minecraft Golden apples have nutritional data? Are tfc potatoes heatable in fireplaces? and is sweetpotato heatable in fireplaces?

**Comment by 0999312** [comment] 2021-03-27 19:23
uncooked items have data, Minecraft Golden apples has data, tfc potatoes is heatable, sweetpotato too
ONLY Pam's foods HAVE NO nutritional data.

**Comment by drhaber** [comment] 2021-03-29 15:43
Can confirm:
tfc-ph_compat uncooked items have nutritional data
Minecraft Golden apples have nutritional data

 tfc potatoes are heatable in the Firepit with two recipes in my instance (I imagine [issue 2](https://github.com/Lebeg134/TFC-PH_Compat/issues/2) plays a part in the two recipes here)
 
 sweetpotato is heatable in the Firepit but has no nutritional data 
 
 Edit:
 All tfc-ph_compat uncooked items have recipes some heatable in the Firepit some in the Firmalife oven
 
 Edit Edit:
 
 Some Pam's items have illogical recipes (I assume this is an indev thing) or rely on vanilla smelting: 
 grilled kebab 
 Cooked Crab
 Fried Chicken 
 Beef wellington
 
 (There are more but I imagine this is not a _Bug_ but instead a pipeline feature)

**Comment by Lebeg134** [comment] 2021-03-29 18:17
[TFC_PH_Compat-1.12.2-1.1.1-dev.jar.zip](https://github.com/Lebeg134/TFC-PH_Compat/files/6223677/TFC_PH_Compat-1.12.2-1.1.1-dev.jar.zip)
I couldn't reproduce the problem on my end but I made a potential fix. Please try out this dev build

**Comment by drhaber** [comment] 2021-03-29 18:20
Testing now...

**Comment by Lebeg134** [comment] 2021-03-29 18:24
By the way I couldn't find those illogical recipes. Cooked crabs rely on vanilla smelting because I didn't modify the recipe because crabs aren't obtainable in TFC as far as I know. 
![image](https://user-images.githubusercontent.com/45501329/112881754-5cd31e80-90cc-11eb-9e50-aaa31cf58afc.png)
Beef wellington and the others have normal recipes in my mod maybe there's an incomplete craft tweaker script somewhere which is overriding some stuff I made

**Comment by drhaber** [comment] 2021-03-29 18:27
Oh I meant like beef wellington has no uncooked version that needs to then be cooked 
The recipe you have above is the same as mine

Crabs -> makes sense

grilled kebab → doesn't use the grill
Fried chicken -> is simply crafted

**Comment by Lebeg134** [comment] 2021-03-29 18:27
Oh yes I haven't done thoose yet.
How is the potencial patch?

**Comment by drhaber** [comment] 2021-03-29 18:28
still loading it is a very large pack ~300 mods

**Comment by drhaber** [comment] 2021-03-29 19:56
Dev build → issue persists

**Comment by drhaber** [comment] 2021-03-29 21:10
<img width="283" alt="Screen Shot 2021-03-29 at 5 09 37 PM" src="https://user-images.githubusercontent.com/56454522/112900464-8cc0f880-90b1-11eb-85e9-60b85501705c.png">
Decided to try out a different configuration and quickly cobbled together a test bench pack with the listed mods and the Dev Build → the issue exists here too

**Comment by drhaber** [comment] 2021-03-29 21:15
Reduced the list again 
<img width="232" alt="Screen Shot 2021-03-29 at 5 15 32 PM" src="https://user-images.githubusercontent.com/56454522/112901145-5fc11580-90b2-11eb-8255-53ad6bb0f90d.png">
Issue persists 


Edit: using version `TFC_PH_Compat-1.12.2-1.1.0.jar` and the same mod list issue does not exist
<img width="492" alt="Screen Shot 2021-03-29 at 5 19 46 PM" src="https://user-images.githubusercontent.com/56454522/112901593-f8f02c00-90b2-11eb-9a70-f1c907cb9c14.png">

**Comment by drhaber** [comment] 2021-03-29 21:31
Removing `TFCStorage-1.0.7.jar` (common mod between RisingInIris2017 and I) and using `TFC_PH_Compat-1.12.2-1.1.0.jar` with this list 
<img width="253" alt="Screen Shot 2021-03-29 at 5 45 22 PM" src="https://user-images.githubusercontent.com/56454522/112904170-8b45ff00-90b6-11eb-925f-1ca6917bc03c.png">

issue persists

**Comment by Lebeg134** [comment] 2021-03-30 08:37
what forge version are you on? try using 14.23.5.2847

**Comment by Lebeg134** [comment] 2021-03-30 09:50
I made another potential fix. Could you try this out as well? ( I still couldn't reproduce the problem even with different forge versions)
[TFC_PH_Compat-1.12.2-1.1.1-dev2.jar.zip](https://github.com/Lebeg134/TFC-PH_Compat/files/6228073/TFC_PH_Compat-1.12.2-1.1.1-dev2.jar.zip)

**Comment by drhaber** [comment] 2021-03-31 00:37
I have been using `14.23.5.2855`
TFC_PH_Compat-1.12.2-1.1.1-dev2.jar

I switched to the version you recommended `14.23.5.2847` used the below list and issue still persists 
<img width="251" alt="Screen Shot 2021-03-30 at 8 37 35 PM" src="https://user-images.githubusercontent.com/56454522/113073764-c409d500-9197-11eb-9aab-413231531666.png">

**Comment by Lebeg134** [comment] 2021-03-31 13:45
I think I finally did it! @RisingInIris2017 helped me to reproduce the problem on my machine and I've indentified a problem and fixed it. @drhaber Could you try it out as well?
[TFC_PH_Compat-1.12.2-1.1.1-dev3.jar.zip](https://github.com/Lebeg134/TFC-PH_Compat/files/6237014/TFC_PH_Compat-1.12.2-1.1.1-dev3.jar.zip)
I don't want to push out the update if it didn't fix all of the bugs mentioned in this issue.

**Comment by drhaber** [comment] 2021-03-31 13:55
Dev3 did not seem to fix the issue

**Comment by Lebeg134** [comment] 2021-03-31 13:58
Could you send over your modlist to download? or give me some logs? maybe I can find something.

Edit: oh and you need to use firmalife 3.0 for the dev3 patch because I updated the compatibility

**Comment by drhaber** [comment] 2021-03-31 14:08
[Mod List](https://drive.google.com/file/d/1gb38osvu6nFtpwObSHCDyItKjmOeEL67/view?usp=sharing) You will have to request access please include your Github handle in the comment if you can 

[2021-03-30-2.log.gz](https://github.com/Lebeg134/TFC-PH_Compat/files/6237169/2021-03-30-2.log.gz)
[2021-03-30-3.log.gz](https://github.com/Lebeg134/TFC-PH_Compat/files/6237170/2021-03-30-3.log.gz)
[debug-2.log.gz](https://github.com/Lebeg134/TFC-PH_Compat/files/6237171/debug-2.log.gz)
[debug.log](https://github.com/Lebeg134/TFC-PH_Compat/files/6237172/debug.log)
[latest.log](https://github.com/Lebeg134/TFC-PH_Compat/files/6237173/latest.log)

Edit: testing with Frimalife 3.1 - issue persists 

How did you reproduce the issue? I wonder if that can shed some light on what makes my system/configuration/pack unique

**Comment by Lebeg134** [comment] 2021-03-31 16:09
I've sent a request for the google drive.

@RisingInIris2017 sent over his mods folder and that reproduced the issue on my machine, then I found why fooddata were not added to the CustomFoods (it had to to with an Enum initializing before Harvestcraft items were defined) I implemented a check for the pre initialization to be finished in order to solve this.

Something Interesting I've noticed in your case is that for my mod your log states that the jar file is not a mod file which is wierd.

**Comment by drhaber** [comment] 2021-03-31 16:17
Load order Def makes sense to me as being part of the problem

I should have been able to successfully above the file request

**Comment by Lebeg134** [comment] 2021-03-31 16:43
I think I know what the problem was on your end. My mod didn't load at all with the modlist you provided to me. I fixed it by renaming the jar file to _TFC_PH_Compat-1.12.2-1.1.1-dev.jar_ from _TFC_PH_Compat-1.12.2-1.1.1-dev3.jar_ I export the dev builds as ...-dev only renamed them in order to distinguish them while you guys debug it. This shouldn't be a problem when I normally release the new version. After fixed the mentioned issue and upgrading to firmalife 3.0 the issue was fixed for me. Could you also test this for me? (Thanks for the help so far btw, I really appreciate it)

**Comment by drhaber** [comment] 2021-03-31 17:07
huh, just noticed that too, the mod is not loading at all even when I change the name to `TFC_PH_Compat-1.12.2-1.1.1-dev.jar`

`FML has found a non-mod file TFC_PH_Compat-1.12.2-1.1.1-dev.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

**Comment by Lebeg134** [comment] 2021-04-01 14:56
I'll close this Issue as the original bug reported was fixed and open a new issue with the mod not registering sometimes

**Closed as completed by Lebeg134** 2021-04-01 14:56 UTC
Labels: bug
